package com.tsb.mbg.entity;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   权限表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_privilege
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SysPrivilege implements Serializable {
    /**
     * <p>权限ID </p>
     * <p>id </p>
     */
    private Long id;

    /**
     * <p>权限名称 </p>
     * <p>privilege_name </p>
     */
    private String privilegeName;

    /**
     * <p>权限URL </p>
     * <p>privilege_url </p>
     */
    private String privilegeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_privilege
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_privilege.id
     *
     * @return the value of sys_privilege.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_privilege.id
     *
     * @param id the value for sys_privilege.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_privilege.privilege_name
     *
     * @return the value of sys_privilege.privilege_name
     *
     * @mbg.generated
     */
    public String getPrivilegeName() {
        return privilegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_privilege.privilege_name
     *
     * @param privilegeName the value for sys_privilege.privilege_name
     *
     * @mbg.generated
     */
    public void setPrivilegeName(String privilegeName) {
        this.privilegeName = privilegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_privilege.privilege_url
     *
     * @return the value of sys_privilege.privilege_url
     *
     * @mbg.generated
     */
    public String getPrivilegeUrl() {
        return privilegeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_privilege.privilege_url
     *
     * @param privilegeUrl the value for sys_privilege.privilege_url
     *
     * @mbg.generated
     */
    public void setPrivilegeUrl(String privilegeUrl) {
        this.privilegeUrl = privilegeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", privilegeName=").append(privilegeName);
        sb.append(", privilegeUrl=").append(privilegeUrl);
        sb.append("]");
        return sb.toString();
    }
}